name: Lint

on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel black flake8 isort
      - name: Run black
        run: black src/soomgogather --check
      - name: Run flake8
        run: flake8 src/soomgogather --config=setup.cfg
      - name: Run isort
        run: isort src/soomgogather -c
